# Generated by Django 5.2.4 on 2025-07-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.CharField(max_length=150)),
                ('resultado', models.CharField(max_length=150)),
                ('dtOfInclusion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
