# Generated by Django 5.2.4 on 2025-07-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_operacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='id',
        ),
        migrations.AddField(
            model_name='operacao',
            name='idOperation',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacao',
            name='idUser',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
