# Generated by Django 5.2.4 on 2025-07-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_remove_operacao_id_operacao_idoperation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='parametros',
            new_name='parameters',
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='resultado',
            new_name='result',
        ),
    ]
